### ISSUE TITLE
Use Taichi (instead of numba and jax) to write real-time simulations in Python?

### ISSUE THREAD

**Issue by neozhaoliang** [williamgilpin/cphy#9]
@williamgilpin Hi, thank you very much for posting your course materials on GitHub, the topics covered in this course are really interesting.

I see there are quite a few animations in this repo, like GOL, Karman vortex, Gray-Scott model, etc. These models are too compute-intensive for Python to animate in real-time, and on the course homepage, you suggested using Numba and Jxx to accelerate. I would suggest using [Taichi](https://github.com/taichi-dev/taichi) as a more suitable option since Taichi's JIT can compile your Python code and execute it on multi-CPU cores and GPUs. See [this doc](https://docs.taichi-lang.org/docs/master/) for an introduction.

+ For the Karman vortex simulation, here is a Python implementation using Taichi  runs in real-time (>40 fps): 
https://github.com/hietwll/LBM_Taichi

+ For the Gray-Scott simulation, here is a Taichi accelerated version that runs in real-time (>200 fps):
https://github.com/taichi-dev/faster-python-with-taichi/blob/main/reaction_diffusion_taichi.py

And there are lots more physical simulations done by the Taichi community:
https://github.com/taichi-dev/awesome-taichi

Hope this information could help you better enjoy the visualizations.

Best.

**Comment by williamgilpin** [comment]
Hi, thanks very much for checking out the course materials! I have always wanted to try Taichi, it looks like an incredible library. I'll look into playing around with it, especially in some more advanced materials later in the course.

**Comment by neozhaoliang** [comment]
Great! I sent you some quick examples via email, hope that can help save your effort to download those examples. :smiley: :

**Comment by williamgilpin** [comment]
Perfect! I haven't gotten the email yet, so if you don't hear from me please let me know so I can make sure it hasn't gotten lost

I should add that I'm very open to PRs modifying the course materials. Right now I'm trying to keep the "core" materials in numpy to make it easier for students new to Python. But Taichi would be perfect to incorporate into a lab, or  an "advanced topic" at the end of existing lectures/notebooks

**Comment by neozhaoliang** [comment]
>  I haven't gotten the email yet, ...

I probably didn't send the email correctly, so here is the code attached to the email:
[taichi-examples.zip](https://github.com/williamgilpin/cphy/files/9475305/taichi-examples.zip)

> Right now I'm trying to keep the "core" materials in NumPy to make it easier for students new to Python.

Fully agree. For starters in Python and NumPy, Taichi might be a bit too advanced,

> But Taichi would be perfect to incorporate into a lab or an "advanced topic" at the end of existing lectures/notebooks.

Yep! If you have any questions about using Taichi or anything that I can help with, feel free to [pull issues](https://github.com/taichi-dev/taichi/issues/) or [contact me](mathzhaoliang@gmail.com).
